spring.application.name=product-purchasing-system

# Perfil por defecto (desarrollo)
spring.profiles.active=dev

server.port=8080

# Settings comunes JPA
spring.jpa.open-in-view=false

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

